services:
  postgres:
    image: postgres:17.4-alpine
    container_name: solidarios_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 811920 # Usar a mesma senha definida no .env
      POSTGRES_DB: solidarios_db # Usar o mesmo nome do banco definido no .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
